services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    volumes:
      - todo_pg_data:/var/lib/postgresql/data

volumes:
  todo_pg_data: {}
